[[targets]]
    name="rosita"
    [[fields]]
        name="Email"
        value="example@domain.com"
    [[fields]]
        name="IP"
        value="10.10.10.01"
    [[fields]]
        name="website"
        value="www.domainname.com"

[[targets]]
    name="veterinaria"
    [[fields]]
        name="Email"
        value="example@veteri.com"
